"""init 13 tables

Revision ID: 99e8050a3229
Revises: 
Create Date: 2026-08-19 14:38:32.735793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e8050a3229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_content',
    sa.Column('brand_story', sa.Text(), nullable=True, comment='品牌故事（富文本）'),
    sa.Column('vision', sa.Text(), server_default='{}', nullable=False, comment='愿景 JSON：{mission,vision,values}'),
    sa.Column('milestones', sa.Text(), server_default='[]', nullable=False, comment='发展历程数组 JSON：[{year,event,sort}]'),
    sa.Column('honors', sa.Text(), server_default='[]', nullable=False, comment='资质荣誉数组 JSON：[{image,desc,sort}]'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_about_content_is_activate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner',
    sa.Column('image_url', sa.String(length=255), nullable=False, comment='图片地址'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=100), nullable=True, comment='副标题'),
    sa.Column('link_type', sa.String(length=20), server_default='none', nullable=False, comment='跳转类型：none/product/news/url'),
    sa.Column('link_target', sa.String(length=255), nullable=True, comment='跳转目标（产品/资讯 ID 或 URL）'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标记（NULL=未删）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint("link_type IN ('none','product','news','url')", name='ck_banner_link_type'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_banner_is_activate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_banner_act_sort', 'banner', ['is_activate', 'sort'], unique=False)
    op.create_table('contact_config',
    sa.Column('phone', sa.String(length=50), nullable=True, comment='联系电话（可多个，逗号分隔）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='公司地址'),
    sa.Column('work_time', sa.String(length=100), nullable=True, comment='工作时间'),
    sa.Column('company_name', sa.String(length=100), nullable=True, comment='企业名称（页脚展示）'),
    sa.Column('icp_no', sa.String(length=100), nullable=True, comment='备案号（页脚展示位）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_contact_config_is_activate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('name', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部门（NULL=顶级）'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='部门编码'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_department_is_activate'),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_department_code', 'department', ['code'], unique=False)
    op.create_index('idx_department_parent', 'department', ['parent_id'], unique=False)
    op.create_table('home_config',
    sa.Column('brand_slogan', sa.String(length=100), nullable=True, comment='品牌定位语'),
    sa.Column('brand_desc', sa.Text(), nullable=True, comment='理念描述'),
    sa.Column('brand_image', sa.String(length=255), nullable=True, comment='配图 URL'),
    sa.Column('advantages', sa.Text(), server_default='[]', nullable=False, comment='核心优势点数组 JSON：[{icon,title,desc}]'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_home_config_is_activate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('company', sa.String(length=100), nullable=True, comment='公司/单位'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='留言内容'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='业务状态：0 待处理 / 1 已处理'),
    sa.Column('handle_note', sa.String(length=500), nullable=True, comment='处理备注'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='提交 IP'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_message_is_activate'),
    sa.CheckConstraint('status IN (0,1)', name='ck_message_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_status_created', 'message', ['status', 'created_date'], unique=False)
    op.create_table('news',
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('summary', sa.String(length=200), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='富文本正文'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='业务状态：1 已发布 / 0 草稿'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_news_is_activate'),
    sa.CheckConstraint('status IN (0,1)', name='ck_news_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_status_published', 'news', ['status', 'published_at'], unique=False)
    op.create_table('product_category',
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_product_category_is_activate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.Text(), server_default='{}', nullable=False, comment='模块级权限矩阵 JSON，如 {"banner":["view","edit"]}'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_role_is_activate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='所属分类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('cover_image', sa.String(length=255), nullable=False, comment='封面图'),
    sa.Column('images', sa.Text(), server_default='[]', nullable=False, comment='图片集数组 JSON'),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格下限'),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格上限'),
    sa.Column('show_price', sa.Integer(), server_default='1', nullable=False, comment='前台是否展示价格：1 展示 / 0 隐藏'),
    sa.Column('brief', sa.String(length=200), nullable=True, comment='核心简介'),
    sa.Column('params', sa.Text(), server_default='[]', nullable=False, comment='规格参数数组 JSON：[{key,value}]'),
    sa.Column('detail_content', sa.Text(), nullable=True, comment='详情图文'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='业务状态：1 上架 / 0 下架'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_product_is_activate'),
    sa.CheckConstraint('show_price IN (0,1)', name='ck_product_show_price'),
    sa.CheckConstraint('status IN (0,1)', name='ck_product_status'),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_cat_status_sort', 'product', ['category_id', 'status', 'sort'], unique=False)
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.Integer(), server_default='0', nullable=False, comment='性别：0 未知 / 1 男 / 2 女'),
    sa.Column('post', sa.String(length=64), nullable=True, comment='岗位名称'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='所属部门'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='所属角色'),
    sa.Column('must_change_pwd', sa.Integer(), server_default='0', nullable=False, comment='是否需强制改密：1 是 / 0 否'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近登录时间'),
    sa.Column('fail_count', sa.Integer(), server_default='0', nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='锁定截止时间'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像 URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('fail_count >= 0', name='ck_sys_user_fail_count'),
    sa.CheckConstraint('gender IN (0,1,2)', name='ck_sys_user_gender'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_sys_user_is_activate'),
    sa.CheckConstraint('must_change_pwd IN (0,1)', name='ck_sys_user_must_change_pwd'),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_dept_role', 'sys_user', ['dept_id', 'role_id', 'is_activate'], unique=False)
    op.create_index('idx_user_role', 'sys_user', ['role_id'], unique=False)
    op.create_table('home_featured_product',
    sa.Column('product_id', sa.Integer(), nullable=False, comment='关联产品'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_home_featured_product_is_activate'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人（账号）'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='操作模块'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作类型（增/删/改/上下线/登录）'),
    sa.Column('target', sa.String(length=255), nullable=True, comment='操作对象摘要'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='状态：1 激活 / 0 禁用'),
    sa.Column('created_at', sa.String(length=64), nullable=True, comment='创建人（写入者登录账号）'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=64), nullable=True, comment='修改人（最后一次修改者登录账号）'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_activate IN (0,1)', name='ck_operation_log_is_activate'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_user_module_time', 'operation_log', ['user_id', 'module', 'created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_log_user_module_time', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_table('home_featured_product')
    op.drop_index('idx_user_role', table_name='sys_user')
    op.drop_index('idx_user_dept_role', table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index('idx_product_cat_status_sort', table_name='product')
    op.drop_table('product')
    op.drop_table('role')
    op.drop_table('product_category')
    op.drop_index('idx_news_status_published', table_name='news')
    op.drop_table('news')
    op.drop_index('idx_message_status_created', table_name='message')
    op.drop_table('message')
    op.drop_table('home_config')
    op.drop_index('idx_department_parent', table_name='department')
    op.drop_index('idx_department_code', table_name='department')
    op.drop_table('department')
    op.drop_table('contact_config')
    op.drop_index('idx_banner_act_sort', table_name='banner')
    op.drop_table('banner')
    op.drop_table('about_content')
    # ### end Alembic commands ###
